export enum PaymentMethodTypes {
    Alipay = 'alipay',
    Au_becs_debit = 'au_becs_debit',
    Bacs_debit = 'bacs_debit',
    Bancontact = 'bancontact',
    Card = 'card',
    Eps = 'eps',
    Fpx = 'fpx',
    Giropay = 'giropay',
    Grabpay = 'grabpay',
    Ideal = 'ideal',
    Oxxo = 'oxxo',
    P24 = 'p24',
    Sepa_debit = 'sepa_debit',
    Sofort = 'sofort',
}